server:
  port: 9001 #服务注册中心端口号

spring:
  profiles:
    active: ${env}
  application:
    name: center
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.96.200:3306/gusteau-live?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root1234
  devtools:
    add-properties: false


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*DAO.xml
  type-aliases-package: com.yueyang.center.domain.*


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
